name: CI - API & Web Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-test:
    name: Run API Automation Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run API Tests
        run: ./gradlew clean apiTest

      - name: Upload API Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-report
          path: build/reports/cucumber/api.html


  web-test:
    name: Run Web Automation Tests
    runs-on: ubuntu-latest
    needs: api-test
    continue-on-error: true   # ðŸ”´ PENTING: web boleh fail, pipeline tetap hijau

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Web Tests (Headless)
        env:
          HEADLESS: "true"
        run: ./gradlew clean webTest

      - name: Upload Web Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-report
          path: build/reports/cucumber/web.html
