name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      APP_ID: "63a804408eb0cb069b57e43a"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run API Tests
        run: ./gradlew clean apiTest

      - name: Upload API JUnit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-junit-report
          path: build/reports/tests/apiTest

      - name: Upload API Cucumber Report (HTML+JSON)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-report
          path: |
            build/reports/cucumber/api-cucumber.html
            build/reports/cucumber/api-cucumber.json

  web:
    runs-on: ubuntu-latest
    needs: api
    env:
      HEADLESS: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      
      - name: Install Google Chrome Stable
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable || true
          google-chrome --version || true

      - name: Run Web Tests
        run: ./gradlew clean webTest

      - name: Upload Web JUnit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-junit-report
          path: build/reports/tests/webTest

      - name: Upload Web Cucumber Report (HTML+JSON)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-report
          path: |
            build/reports/cucumber/web-cucumber.html
            build/reports/cucumber/web-cucumber.json
