name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run API Tests
        run: ./gradlew clean apiTest

      - name: Upload API Test Report (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: build/reports/tests/apiTest

  web:
    runs-on: ubuntu-latest
    needs: api
    env:
      HEADLESS: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Chrome sudah ada di ubuntu-latest biasanya, tapi step ini bikin lebih stabil
      - name: Check Chrome Version
        run: google-chrome --version || chromium-browser --version || true

      - name: Run Web Tests
        run: ./gradlew clean webTest

      - name: Upload Web Test Report (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-test-report
          path: build/reports/tests/webTest
